version: '3'

services:
  db:
    image: postgres
    volumes:
      - doctor-is-db:/var/lib/pgsql/data
  web:
    image: app
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py migrate && python populate.py && python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  doctor-is-db:
